/**
 * IceLogoServiceTestCase.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.computationalproteomics.icelogoserver.soap.client.wsdl2java;

public class IceLogoServiceTestCase extends junit.framework.TestCase {

    private String[] iHumanGranzymeBSubstrates = new String[]{"GHISVKEPTPSIASDISLPIATQELRQRLR","EREMFDKASLKLGLDKAVLQSMSGRENATN","XXXXXXMSDIVVVTDLIAVGLKRGSDELLS","GQDQEEEEIEDILMDTEEELMRAEDTEQLK","ESYATDNEKMTSTPETLLEEIEAKNRELIA","VENKERTLKRLLLQDQENSLQDNRTSSDSP","SALRDDERRESATADAGYAILEKKGALAER","XXXXXXXXXMEVTGDAGVPESGEIRTLKPC","XXXXXMAVESRVTQEEIKKEPEKPIDREKT","XXXXXXMAGPRVEVDGSIMEGGGQILRVST","RAIVDVHFDPTTAFRAPDVARALLRQIQVS","HLRGFANQHSRVDPEELFTKLDRIGKGSFG","GDGDEEGENEEEEEDAEAGSEKEEEARLAA","XXMSHVAVENALGLDQQFAGLDLNSSDNQS","LLKRRNVPHEDICEDSDIDGDYRVQNTSLE","GPCGVPAAGGPPTGDEASSLGTAQAASTSG","PCGVPAAGGPPTGDEASSLGTAQAASTSGL","DTNHNEEDDEEPIPESSELTLQELLGDERR","VKAMAQEDSESLEEDSSSEEEDETPAQATP","GALSEEEAQALLSGDTQTDTTSFYDRVWAA","DTDLYDEFGNYIGPELDSDEDDDELGRETK","DLYDEFGNYIGPELDSDEDDDELGRETKDL","PGVQMQAIPEDAIPEESGDEDEEDPDKRIS","ARLIPDTVLVDLVSDSDEEVLEVADPVEVP","VPVARLPAPAKPEQDSDSDSEGAAEGPAGA","LPDGCEGRGLSVHTDMASVTKAMAAPESGL","HMECEIKLEGPVSPDVEPGKEETEESKKRK","FIQEPAKNRPGPQTRSDLLLSGRDWNTLIV","RLTEEEEAEPGTEVDLAVLADLALTPARRG","EGDDKDDYWREQQEKLEIEKRAIVEDHSLV","GVGGGAASSVQVQGDNTSDLDFGAVQRGDP","DDYLNTPLLDEIDPDSAEEPPVSRRLFLDG","MMVPGMEGKEEPGSDSGTTAVVALIRGKQL","TQEAVNGHGALEVDMALGSPEMDVRKKKKK","PQVTEAEEEEAPCCSSSVSGGAASSSPAAG","QVTEAEEEEAPCCSSSVSGGAASSSPAAGI","EERDEEEEGNIVDAEAEEGDADASDTKRKE","LLKRRNVPQEDICEDSDIDGDYRVQNTSLE","SGEEEEDEEGYNDGEVDDEEDEEEAGEEEG","EEEEDEEGYNDGEVDDEEDEEEAGEEEGSQ","EEDEEGYNDGEVDDEEDEEEAGEEEGSQKR","AGEEEEKEAGIVHSDAEKEQEEEEQKQEME","SDRSRKRELKEVFGDDSEISKESSGVKKRR","DRSRKRELKEVFGDDSEISKESSGVKKRRI","QDINLNSPNKGLLSDSMTDVPVDTGVAART","LQASPAKPSGETAADSMIPEEEDDEDDEDG","SVLDNFKFLESAAADFSDEDEDDDVDGREK","SGEDRDTKEALKEFDFLVTSEEGDNESRSA","GLGELAGLTVANEADSLTYDIANNKDALRK","DPFTSETVDPEMEGDDNLGGEDKKETPEEV","GGEDKKETPEEVAADVLAEVITAAVRAVDG","TYNDSDGGTAWVSQESFEADEPDSRAGVKW","DGVEVSVTTSKIVTDSDSKTEELRFLRRQE","SVLDNFKFLESAAADFSDEDEDEDTDGRAK","TSEDRDTKEALKEFDFLVTSEEGDNESRSA","GLGELAGLTVANEADSLAYDIANNKDALRK","LTSSRVCFPERILEDSGFDEQQEFRSRCSS","PLSPTMEEEPLVVFLSGEDDPEKIEERKKS","YSVYVYKVLKQVHPDTGISSKAMGIMNSFV","LKHLEPEPEEEIIAEDYDDDPVDYEATRLE","KHLEPEPEEEIIAEDYDDDPVDYEATRLEG","EPSLKNSNPDEIEIDFETLKPSTLRELERY","LPGSLQRSRSDIDVNAAAGAKAHHAAGQSV","DLERRREESQTQIRDVMVWSNERVMGWVSG","DIYHCPNCEKTHGKSTLKKKRTWHKHGPGQ","VFREFFGGRDPFSFDFFEDPFEDFFGNRRG","RSTTLDAGNIKLAFNSLLEKAEAREREREK","GKKAALDEAQGVGLDSTGYYDQEIYGGSDS","GSGWAETPRTDRGGDSIGETPTPGASKRKS","PDDIQYFDKLLVDVDESTLSPEEQKERKIM","RSRRERVRQSRMDTDLETMDLDQGGEALAP","IRMLRSPTLYGISHDDLKGDPLLDQRRLDL","AAAAAAGDSDSWDADAFSVEDPVRKVGGGG","EESDLELAKETFGVNNAVYGIDAMNPSSRD","MDKMMVAGFKKQMADTGKLNTLLQRAPQCL","TEMGPPPSPASTCSDASSIASSASMPYKRR","DSDSSSSQSDDIEQETFMLDEPLERTTNSS","NRKRHGSSRSVVDMDLDDTDDGDDNAPLFY","ADLSKYNLDASEEEDSNKKKSNRRSRSKSR","DLLDRQILAADAGADAGQLDLVDQIDQRNL","QEGDEEEEGHIVDAEAEEGDADASDAKRKE","SVVLSMDNNRNLDLDSIIAEVKAQYEDIAN","TAVVQAAYCAPKKEKVAIKRINLEKCQTSM","GHSEASLASALVEGEIAEEAAEKATSRGSN","NSGMDSNIDLTIVEDEEEESVALEQAQKVR","VERDDGSTLMEIDGDKGKQGGPTYYIDTNA","QLVENTDETYCIDNEALYDICFRTLKLTTP","ETGAGKHVPRAVFVDLEPTVIDEVRTGTYR","DEVRTGTYRQLFHPEQLITGKEDAANNYAR","SITASLRFDGALNVDLTEFQTNLVPYPRIH","QLLDDYPKCFIVGADNVGSKQMQQIRMSLR","RAKQEQEAKQKLEEDAEMKSLEEKIGCLLK","LYAVKILKKDVVIQDDDVECTMVEKRVLAL","YRRLLEDGEDFNLGDALDSSNSMQTIQKTT","SVVLSMDNSRSLDMDSIIAEVKAQYEDIAN","APPPPPPPEEDPEQDSGPEDLPLVRLEFEE","XXXXXXXXMSDAAVDTSSEITTKDLKEKKE","XXXXXXMSDAAVDTSSEITTKDLKEKKEVV","XXMSDAAVDTSSEITTKDLKEKKEVVEEAE","SDAAVDTSSEITTKDLKEKKEVVEEAENGR","AAVDTSSEITTKDLKEKKEVVEEAENGRDA","VDTSSEITTKDLKEKKEVVEEAENGRDAPA","DTSSEITTKDLKEKKEVVEEAENGRDAPAN","GEQEADNEVDEEEEEGGEEEEEEEEGDGEE","EADNEVDEEEEEGGEEEEEEEEGDGEEEDG","NEVDEEEEEGGEEEEEEEEGDGEEEDGDED","DEEEEEGGEEEEEEEEGDGEEEDGDEDEEA","EEEGGEEEEEEEEGDGEEEDGDEDEEAESA","EEEEEEEEGDGEEEDGDEDEEAESATGKRA","EEEEEEEGDGEEEDGDEDEEAESATGKRAA","REIFDSRGNPTVEVDLFTSKGLFRAAVPSG","PVHISGQHLVAVEEDAESEDEEEEDVKLLS","YSIYVYKVLKQVHPDTGISSKAMGIMNSFV","SDEHGIDPTGTYHGDSDLQLDRISVYYNEA","PDNFVFGQSGAGNNWAKGHYTEGAELVDSV","NWAKGHYTEGAELVDSVLDVVRKEAESCDC","PGNPPAEIGQNISSNSSASILESKSLYDEV","LTFGFVRADDEVDVDGTVEEDLGKSREGSR","VSNNVPGSDFSVGADTALNTICTTCDRIKQ","PDYWIDGSNRDPLGDFFEVESELGRGATSI","ERERKEELRGGGGDMAEPSEAGDAPPDDGP","GVRLLQDSVDFSLADAINTEFKNTRTNEKV","DQLTNDKARVEVERDNLAEDIMRLREKLQE","QELQAQIQEQHVQIDVDVSKPDLTAALRDV","LQAQIQEQHVQIDVDVSKPDLTAALRDVRQ","TEYRRQVQSLTCEVDALKGTNESLERQMRE","TLRGQVGGQVSVEVDSAPGTDLAKILSDMR","LGRTLGLYGKDQQEAALVDMVNDGVEDLRC","EEDEDDEDEDDEEEDDEDDDEEEEEEEPVK","RTLLAKNLSFNITEDELKEVFEDAMEIRLV","KSKGIAYIEFKSEADAEKNLEEKQGAEIDG","SQPSKTLFVKGLSEDTTEETLKESFEGSVR","SGAGSEDMGTTVNGDVFQEANGPADGYAAI","IVDKYRDGTKMVSADAYKITPGARGAFSEE","SNFGGGGSYNDFGNYNNQSSNFGPMKGGNF","XXXXXXMAGGKAGKDSGKAKTKAVSRSQRA","NSANCLEEKGPMFELLPGESNKIPRLRTDL","PTRPTDKPLRLPLQDVYKIGGIGTVPVGRV","GKKLEDGPKFLKSGDAAIVDMVPGKPMCVE","AAIVDMVPGKPMCVESFSDYPPLGRFAVRD","AALRTGDDYVAIGADEEELGSQIEEAIYQE","IANAHRKPLVIIAEDVDGEALSTLVLNRLK","PKSKELVSSSSSGSDSDSEVEKKLKRKKQA","SKELVSSSSSGSDSDSEVEKKLKRKKQAVP","PPYRGRSSESSCGVDGDYEDAELNPRFLKD","YRGRSSESSCGVDGDYEDAELNPRFLKDNL","VPDDKKPNGRKVVGDVAYDEAKERASFITP","LQRSKKGKLPIVNEDDELVAIIARTDLKKN","SGAGKAIGVLTSGGDAQGMNAAVRAVTRMG","ISNNVPGTDFSLGSDTAVNAAMESCDRIKQ","NKHNRLYMKARPFPDGLAEDIDKGEVSARQ","XXMIIYRDLISHDEMFSDIYKIREIADGLC","SDIYKIREIADGLCLEVEGKMVSRTEGNID","EERDQDKKRRVVDTESGAAAAVEKLEEVTA","AGPKTLKKKVPAVPETLKKKRRNFAELKVK","GALSEAEAQALLSGDTQTDATSFYDRVWAA","VSVETQGDDWDTDPDFVNDISEKEQRWGAK","SEKDIQDLKFGVEQDVDMVFASFIRKASDV","LTFGSVRADDEVDVDGTVEEDLGKSREGSR","EDLYDCVENEEAEGDEIYEDLMRSEPVSMP","LTPDLWKETVFTKSPYQEFTDHLVKTHTRV","LGSLELVEDDTVDSDATNGLIDLLEQEEGQ","REIFDSRGNPTVEVDLYTAKGLFRAAVPSG","WQKFTASAGIQVVGDDLTVTNPKRIAKAAS","REILDSRGNPTVEVDLYTAKGLFRAAVPSG","WSKFTANVGIQIVGDDLTVTNPKRIERAVE","XXXXXXXXMDGIVPDIAVGTKRGSDELFST","QSGNLALAASAAAVDAGMAMAGQSPVLRII","LYAIKILKKDVVIQDDDVECTMVEKRVLAL","SANHNILQIVDVCHDVEKDEKLIRLMEEIM","LGQAEEVVQERICDDELILIKNTKARTSAS","EGVEEKKKEVPAVPETLKKKRRNFAELKIK","KTKSHDDGNIDLESDSFLKFDSEPSAVALE","XXXXXXMPKRKVSADGAAKAEPKRRSARLS","SFVSSSDRLRELGPDGEEAEGPGAGDGPPR","KNAESNAELKGLDVDSLVIEHIQVNKAPKM","RTLLAKNLPYKVTQDELKEVFEDAAEIRLV","KSKGIAYIEFKTEADAEKTFEEKQGTEIDG","SQPSKTLFVKGLSEDTTEETLKESFDGSVR","PVPTFQPFQRSMSADEDLQEPSRRPQRKSL","SEGDFSADTSEINSNSDSLNSSSLLMNGLR","VRLRSSVPGVRLLQDSVDFSLADAINTEFK","PPPRGGTRGQEPQMKETIMNQEKLAKLQAQ","YGSVLMGKSNESGELVAIKRMKRKFYSWDE","LQRSKKGKLPIVNDCDELVAIIARTDLKKN","WTSFLSGVDIQIVGDDLTVTNPKRIAQAVE","PHRHEGVFICRGKEDALVTKNLVPGESVYG","KHLKRVAAPKHWMLDKLTGVFAPRPSTGPH","YDTKGRFAVHRITVEEAKYKLCKVRKITVG","FKDIDIEDLEELDPDFIMAKQVEQLEKEKK","EFWKQLCAEHGISPEGIVEEFATEGTDRKD","SDKTDTDWRARPATDSFDDYPPRRGDDSFG","LDDVELREAQRDYLDFLDDEEDQGIYQSKV","LDDVELREAQRDYLDFLDDEEDQGIYQNKV","LRMHQYRAPGEQDGDALPLGSSVDILATDD","GEQDGDALPLGSSVDILATDDPDFTQDDQQ","DDSQEKTDDSQETQDSQKVELSEPRLKAFK","EPSLRDSNPEEIEIDFETLKPSTLRELERY","AEMSSILEERILGADTSVDLEETGRVLSIG","IIGDRQTGKTSIAIDTIINQKRFNDGSDEK","EEEEEEEEGDGEEEDGDEDEEAEAPTGKRV","GQIPATALLPTMTPDGLAVTPTPVPVVGSQ","IPATALLPTMTPDGLAVTPTPVPVVGSQMT","ATALLPTMTPDGLAVTPTPVPVVGSQMTRQ","LILFPRKPSAPKKGDSSAEELKLATQLTGP","AVNSVQSGNLALAASAAAVDAGMAMAGQSP","NLALAASAAAVDAGMAMAGQSPVLRIIVEN","PMSAPSRSSGALSVDKKPTSTKPSSSAPRV","AKVDEFPLCGHMVSDEYEQLSSEALEAARI","IHISKKWGFTKFNADEFEDMVAEKRLIPDG","HISKKWGFTKFNADEFEDMVAEKRLIPDGC","RLEQQVPVNQVFGQDEMIDVIGVTKGKGYK","QVPVNQVFGQDEMIDVIGVTKGKGYKGVTS","LGQIGPAPPLKVHVDCMTSQKLVRLPGLID","XXXXXXXMADLSLADALTEPSPDIEGEIKR","VTLAKDMQPSMESDMALVKDMELPTEKEVA","LAKDMQPSMESDMALVKDMELPTEKEVALV","ITGTGKKCSLPAEEDSVLEKLGERKPCNSQ","WDDDDAPRPSQFEEDLALMEEMEAEHRLQE","XXXXXXXXXXMADPDVLTEVPAALKRLAKY","FREHQFTKIDTIAADESFTQMDLGDRILKL","DSSVSYIDSAVISPDTVPLGTGTSILSKQV","LRRRTFSYDEIHGQDSGAEDSIAKQIESLE","SPPQMHSSAIPLDFDVSSPLTYGTPSSRVE","XXMSGFDDPGIFYSDSFGGDAQADEGQARK","NHFSIMQQRRLKDQDQDEDEEEKEKRGRRK","GALARGDDETLHKNNALKVVRELQAQIAEL","LSQRYYEDLDEVSSTSSVSQSLESEDARTS","RSRILKAGGKILTFDQLALESPKGRGTVLL","DTGLAPPALWDLAADKQTLQSEQPLQVARC","NVTLPAVFKAPIRPDIVNFVHTNLRKNNRQ","RRIQRRGPCIIYNEDNGIIKAFRNIPGITL","EDEEEEGEEEDVSGEEEEDEEGYNDGEVDD","SGEEEEDEEGYNDGEVDDEEDEEELGEEER","EEEEDEEGYNDGEVDDEEDEEELGEEERGQ","RQLEDILSTYCVDNNQGGPGEDGAQGEPAE","STYCVDNNQGGPGEDGAQGEPAEPEDAEKS","IPPPYDKKKRMVVPAALKVVRLKPTRKFAY","SKPAAQTPPASIEVDENIELISGQNERMGP","FPVGAATLVDEVGVDVAKHVAEDLGKVFGE","GLIHRKTVGVEPAADGKGVVVVMKRRSGQR","VRKLKEDKAPQVDVDKAVAELKARKRVLEA","HSDAQALVLLDVTPDQSMVDEGMAREVINR","LDELSRYPEDKITPENLPQILLQLKRRRTE","MMLTSDQKPDVMYADIGGMDIQKQEVREAV","SLSDEAPVLPNTTPDLLLVTTANPSAPGTD","AMNRHIKASTKVEVDMEKAESLQVTRGDFL","XXXXXXXXXXXXMGFVKVVKNKAYFKRYQV","GKTDYYARKRLVIQDKNKYNTPKYRMIVRV","GMDKIYEGQVEVTGDEYNVESIDGQPGAFT","GLIHRKTVGVEPAADGKGVVVVIKRRSGQR","LGIGKAIAVLTSGGDAQGMNAAVRAVVRVG","VSNNVPGSDFSIGADTALNTICTTCDRIKQ","CGYLATMAGLAAGADAAYIFEEPFTIRDLQ","LSLFTSLGLSEQKARETLKNSALSAQLREA","DMQVLHLLGPKLEADLEKKFKVAKARLEET","KQLRKPRHQEGEIFDTEKEKYEITEQRKAD","PRKPSAPKKGDSSAEELKLATQLTGPVMPI","NLLPQPPRSKYIHPDDELVLEDELQRIKLK","ENEEEEIGNLELAWDMLDLAKIIFKRQETK","GSGDAVPSGNEVSENMEEEAENQAESRAAV","KEGVIKIRSVASREEVAIKRENFVAEIQKR","EPEPDYEPEPETEPDYEDVGELDRQDEDAE","XXMSGFDDPGIFYSDSFGGDPGAEEGQARK","GDGMERDYRAIPELDAYEAEGLALDDEDVE","IPELDAYEAEGLALDDEDVEELTASQREAA","QLSKEKADFTVVAGDEGSSTTGGSSEENKG","RNVTTKNYSEVIEVDESDVEEDIFPTTSKT","HEKAEFEVHEVYAVDVLVSSGEGKAKDAGQ","PNGPMRITSGPFEPDLYKSEMEVQDAELKA","SAPKTDMDNQIVVSDYAQMDRVLREERAYI","PRGTLRRDFNHINVELSLLGKKKKRLRVDK","PTLPVEEKKKIPDPDSDDVSEVDARHIIEN","HLTVKKIFVGGIKEDTEEYNLRDYFEKYGK","KARKTGLITPKAGFDSDYDQALADIRENEQ","DSVVMAEAPPGVETDLIDVGFTDDVKKGGP","IQLSMQGSSRNISQDMTQTSGTNLTSEELR","KQEGSSDDASSGVGDSDSEDLGTFGKGAPK","EPPGELADISDVEGEVGAIGEEAPQMNYIQ","MADIDNKEQSELDQDLDDVEEVEEEETGEE","MQNPQILAALQERLDGLVETPTGYIESLPR","QACRGTELDDGIQADSGPINDTDANPRYKI","ASDNQPEGMISESLDNLESMMPNKVRKIGE","GNRSSHSRLGRIEADSESQEDIIRNIARHL","FGRTTTPQQTKITQDIFQQLLKRGFVLQDT","EDEEDDSEDAINEFDFLGSGEDGEGSPDPR","RPRHQGVMVGMGQKDSYVGDEAQSKRGILT","XXXXMDDDIAALVVDNGSGMCKAGFAGDDA","IVRDIKEKLCYVALDFEQEMATAASSSSLE","AASSSSLEKSYELPDGQVITIGNERFRCPE","SDGLKGRVFEVSLADLQNDEVAFRKFKLIT","LRQKYNVRSMPIRKDDEVQVVRGHYKGQQI","NTETNGEFGKRPAEDMEEEQAFKRSRNTDE","GYDYSYAGGRGSYGDLGGPIITTQVTIPKD","FESGISQALLELEMNSDLKAQLRELNITAA","KQKRPRSRTLTAVHDAILEDLVFPSEIVGK","RSRTLTAVHDAILEDLVFPSEIVGKRIRVK","NGTIDFPEFLTMMARKMKDTDSEEEIREAF","ALPLGRKKGAKLTPEEEEILNKKRSKKIQK","XXXXXXMVRMNVLADALKSINNAEKRGKRQ","ASHAKGIVLEKVGVEAKQPNSAIRKCVRVQ","PYRRSVPTWLKLTSDDVKEQIYKLAKKGLT","QPTIFQNKKRVLLGETGKEKLPRYYKNIGL","YDTKGRFAVHRITPEEAKYKLCKVRKIFVG","IDLETGKITDFIKFDTGNLCMVTGGANLGR","XXMCEEEDSTALVCDNGSGLCKAGFAGDDA","ERKRKSVRGCIVDANLSVLNLVIVKKGEKD","IKGRLNRLPAAGVGDMVMATVKKGKPELRK","RKFTYRGVDLDQLLDMSYEQLMQLYSARQR","YRGVDLDQLLDMSYEQLMQLYSARQRRRLN","KRTFRKFTYRGVDLDQLLDMSYEQLMQLYS","RCVPKDKAIKKFVIRNIVEAAAVRDISEAS","XXXXXXXXXXXMAQDQGEKENPMRELRIRK","YARRPQYSNPPVQGEVMEGADNQGAGEQGR","RFRRGPPRQRQPREDGNEEDKENQGDETQG","PREDGNEEDKENQGDETQGQQPPQRRYRRN","XXXXXXXXXXXMQNDAGEFVDLYVPRKCSA","XXXXXXXMADDLDFETGDAGASATFPMQCS","XXXXMADDLDFETGDAGASATFPMQCSALR","XXXXMEEEIAALVIDNGSGMCKAGFAGDDA","XXXMCEEETTALVCDNGSGLCKAGFAGDDA","RLGNDFHTNKRVCEEIAIIPSKKLRNKIAG","YGRRPQYSNPPVQGEVMEGADNQGAGEQGR","TGAGKHVPRAVFVDLEPTVIDEVRTGTYRQ","THTTLEHSDCAFMVDNEAIYDICRRNLDIE","TTLEHSDCAFMVDNEAIYDICRRNLDIERP","VGINYQPPTVVPGGDLAKVQRAVCMLSNTT","ETGAGKHVPRAVFVDLEPTVIDEIRNGPYR","DEIRNGPYRQLFHPEQLITGKEDAANNYAR","ACISIGNQNFEVKADDLEPIVELGRGAYGV","QALQAGELESQAAPDEAQGDPELGAVELRI","GVQMQAIPEDAVHEDSGDEDGEDPDKRISI","TQTATQQAQLAAAAEIDEEPVSKAKQSRSE","PKSENRDKKEKPKPDAYDMMVRELGFEMKA","KREKEIKSELKMKQDAQVVLYRSYRHGDLP","EEKKDKEKKEIKKERKELKKDEGRKEEKKD","SPARPPSPRLDVSSDSFDPLLALYAPRLPP","XXXXXXXXXMKVELCSFSGYKIYPGHGRRY","QSLSNSFNSSYMSSDNESDIEDEDLRLELR","SVLRCGKKKVWLDPNETNEIANANSRQQIR","AGAGSSGGSSGVSGDSAVAGAAPALVAAAA","GDGMERDYRPIPELDVYEAEGLALDDEDVE","KDEIQDEEDDDDYVDEGEEEEEEEEEGLRG","IQDEEDDDDYVDEGEEEEEEEEEGLRGEKR","EGGGGGGRPGAPAGDGKTEQKGGDKKRGVK","VSNNVPGSDFSIGADTALNTITDTCDRIKQ","NVPGSDFSIGADTALNTITDTCDRIKQSAS","CGYLANMGGLAAGADAAYIFEEPFDIRDLQ","KLKEARGRGKKFTTDDSICVLGISKRNVIF","PLDPTRLQGINCGPDFTPSFANLGRTTLST","GFSSPPRIKDEPEDDGYFAPPKEDIKPLKR","FFAIKALKKDVVLMDDDVECTMVEKRVLSL","YSAIKALKKDVVLIDDDVECTMVEKRVLTL","APDPALVPPQEIAPDASFIDDEAFKRLQGK","EVHKQQDMDLDIEFDVHLGIAHTRWATHGE","ASPKYEFWGPLYIQETGEEEVFTQDPRKRQ","ASEEGADRNGGPGEDAAEGQTKTAAGKRKR","EDDDGEIDDGEIDDDDLEEGEVKDPSDRKV","EEELRQIKINEVQTDVGVDTKHQTLQGVAF","AALEKLFPDTPLALDANKKKRAPVPVRGGP","PKRKRKNSRVTFSEDDEIINPEDVDPSVGR","DFPIPLPEDDSIEADILAITGPEDQPGSLE","LTDDPDTEEALKEFDFLVTAEDGEGAGEAR","GGGHGSGSPSQPDADSHFEQLMVSMLEERD","IMKELNKRGRVLVNDAQKVTEGQQERLERQ","QRMRVSSGERWIKGDKSELNEIKENQRSPV","FFKWQTKPKLTIHGDLYYEGKEFETRLKEK","AAGDPKKEKKSLDSDESEDEEDDYQQKRKG","PDNFIFGQSGAGNNWAKGHYTEGAELVDSV","NWAKGHYTEGAELVDSVLDVVRKECENCDC","QLVENTDETYCIDNEALYDICFRTLKLATP","PEMEDANSEKSINEENGEVSEDQSQNKHSR","HSDDYIKFLRSIRPDNMSEYSKQMQRFNVG","QQLVASHLEKLLGPDAAINLTDPDGALAKR","GRKKKMSNALAIQVDSEGKIKYDAIARQGQ","TQATTQQAQLAAAAEIDEEPVSKAKQSRSE","ATTQQAQLAAAAEIDEEPVSKAKQSRSEKK","NWAKGHYTEGAELVDSVLDVVRKESESCDC","QLVENTDETYSIDNEALYDICFRTLKLTTP","ILQQARQQQEELEAEHGTGDKPAAPRERTT","EGGSAESEGAKIDASKNEEDEGHSNSSPRH","EFQDVIPPDDFLTSDEEVDSVLFGSLRGHV","VRTMLDEDDVKVAVDVLKELEALMPSAAGQ","DLPISRENLTDLVVDTDTLGESTQPQREGA","LPDGQEYQRIEFGVDEVIEPSDTLPRTPSY","KRSSSEDDDLDVESDFDDASINSYSVSDGS","PEIRKRYDQDLCYTDILFTEQERGVGIKST","AAATNHTTDNGVGPEEESVDPNQYYKIRSQ","MVQDDDAAQGVISASASNLDDFYPAEEDTK","RALQADQLENQAAPDDTQGSPDLGAVELRI","QDPEQEEVELAPVGDGDVVADIQDRIQALG","SESPSASVAEATTTDVQVTPTALLQLDREQ","SNPEARLNEKNPDVDAICEMPSLSRKNDLI","EGDDVQTAAEEVLADGDTLDFEDDTVQSSG","DDVQTAAEEVLADGDTLDFEDDTVQSSGPR","ADRCTLPEHESPSQDISDACEAESTERCEM","EREMFDRASLKLGLDKAVLQSMSGRESNVG","IVDKSGVVRVRVEGDNDKKNPREEGMVPFI","TYQPESSEEAEAEDDVGGEEEGDPERSVTD","SILKSRSRENSVCSDTSESSAADVEDRRGL","AVQRARQIAAKIGGDAATTVNNNTPDFGFG","DEDKPDETGFITPADSGLITPGGFSSVPAG","ASGDPKKEKKSLDSDESEDEDDDYQQKRKG","PPPVSSSDSEAPEADLGCGSDVDKDKESRR","EDGNYSAVGFTYGSDYYDPSEPTEEEEPSK","DLETGDVHKGKPGPDTQSEDIEEEEVKEET","TCRDANEELNCQDPDVGDMEEEERLQVTDK","PCPSPSPRRTSPAPDILSLPEDPCLGPRNE","EAEQLEPRVSALEEDMDDVESSEEEEEEDE","QEEPAAAPEPRKETESEAEDDNLDDLERHL","EPAAAPEPRKETESEAEDDNLDDLERHLRE","GSFGKVYKGRCRNKIVAIKRYRANTYCSKS","SSIQAAVRQLEAEADAIIQMSESSQSEASV","RCVPTDKAIKKFVIRNIVEAAAVRDISEVS","SSPGEESEVGSMVGEGFIEVLTKKQRRLLE","KPAAERCLEQLVFGDVEDDEDALLQRLRSS","KDIFSQKKKQPVWVDEDDEDEEIVDMSNNR","IFSQKKKQPVWVDEDDEDEEIVDMSNNRFR","PDWAEAGSKRRTSSDDESEEDEDDLLQRTG","NLNHYGMTHVASVSDVLLDNAFTPPCQRMG","LRTSPADHGGSVGSESGGSAVDSVAGEHSV","QEDQTSDKNEGISEDMGDEAKEERQESRAS","EYAKIHDLLKTIGLDIGVAEISQLAARTQE","KSLASKGVPNVISEDTLKGQDSLSTDTGQS","GRPTEDEDDKDKVADEDDVDNEEAALLHEE","DEDDVDNEEAALLHEEATMTIEELLTRYGQ","PVSNSRARKRIIEPDDFLDDLDDEDYEEDT","EPSAPDCRHLKVEADAEKPGPADRKGGLGM","RNVAPKNYSETIEVDDSDEDDIFPTNSRAD","LRVAPYRPDQQVEEDDDFMDENQGKGIRVL","FLDNGPKTINQIRQDAVKDLGVFIPAPMAQ","GSCSSSSRLPAPQEDTASEAGTPQGEVQTR","YNKAVECCDKALGLDSANEKGLYRRGEAQL","AAAAAAGDSDSWDADTFSMEDPVRKVAGGG","RLMPNSQKDCHCLGDVLIENTKESKSQSED","RTNPEYENEVEASMDMDLLESSNISEGEIE","TKLEETIAEETPSQDEEEGVSDVESERSQE","NPETKPARPDPIDMDEDELEMLSEARARLA","GLPAPKNDFEIVLPENAEKELEEREIDDTY","VFKAPAPRPSLLGLDLLASLKRREREEKDD","GYCKLKVFNPRIGMDALQIYPISQANANQR","ANDMEDDSMDLIDSDELLDPEDLKKPDPAS","SGAGSEDMSTTVNGDVFQEANGPADGYAAI","STVNEKPKYAEISSDEDNDSDEAFESSRKR","IKLPSSVFASEFEEDVGLLNKAAPVSGPRL","ERWLSASVNDDVDTDEESAQLRGSKRIGDG","DRDYMDTLPPTVGDDVGKGAAPNVVYTYTG","IPPPYDKKKRMVVPAALKVVRLKPTRKFAL","RAAALDAGNIKLTFNSLLEKAEAREREREK","QLDPSRLPGINCGPDFTPSFANLGRPALSN","DSPQTRTASGAVDEDALTLEELEEQQRRIW","KAKIMAKKRSTIKTDLDDDITALKQRSFVD","DLNGLLVPDPLCSGDSTSANKTGLRTMPPI","GPGNPVPGPLAPLPDYMSEEKLQEKARKWQ","KKAKGGNVFEALIQDDSEEEEEEEENRVLK","KAKGGNVFEALIQDDSEEEEEEEENRVLKP","EEEEEEEEPVQSKGDSIEEILADSEDEDEE","XXMALFHIARYAGPEAAGQGDTDAEAGSRA","PKIPKSKRQKKELGDSSGEGPEFVEEEEEV","EDRDWQDDQSDNQSDYSVASEEGDEDFDER","FRKTLEKEAKGEEPDIAVPKFKQRKGESDG","QQLMSKDQDEQEELDFLFDEEMEQMDGRKN","VIPVTSTTNKITAEDCTMEVTPGAEIQDGR","PDLVDDGEDESAEHDEYIDGDEKNLMRERI","TNKKEGEKTDRVGVEASEETPQTSSSSARP","FWEPVESTQEVVCTDNATEKEEEADGGGQA","AAPAAAAPPPAPATDSASGPSSDSGPEAGS","LKEGGDDGLHSAEQDADDEAADDTDDTSSV","LSDPSDIIRVTVGGDAAAAAVAAAAAAAAT","DREDGELEEGELEDDGAEEVQDPPGGQERS","QAEEHGLARKKPAPDAQAESGPGDGGGEPD","MDGRKNTFTAWSEEDSDYEIDDRDVNKILI","EVPPGPPRFQQVPTDALANKLFGAPEPSTI","DLRGKKKEELLKQLDDLKVELSQLRVAKVT","XXXXXXMAGGKAGKDSGKAKAKAVSRSQRA","ATEAPARPLNCVEAEAAVGAAAEDSCDARG","DDRLEDDDFDLIEENLGVKVKRGQKYRRVK","SASLAKKKPLFITTDSSKLVSGVLGSALTS","EVLSSQEMQVENELEDLIDELLERDGGSGN","SSIQAAVRQLEAEADAIIQMVREGQRARRQ","XXXMSAQAQMRAMLDQLMGTSRDGDTTRQR","SSPGEENEASSVVGEGFIEVLTKKQRRLLE","EEEEELGDEAMMALDQNLASLFKEQKMRIQ","SEGTTPEKNAASQQDAVTEGAMPAATGKDQ","PLGSDSEGVNCLAYDEAIMAQQDRIQQEIA","VGPKRKEEAIIIVEDEDEDDKESVRRRQRR","APGESALDDCAPSGDSQSDEPPSSEDSLPR","KSKSPPKVPIVIQDDSLPAGPPPQIRILKR","FSGSSTFSPTILSSDKETIEIIDLAKKDLE","KPGVMTQEVGQLLQDMGDDVYQQYRSLTRQ","TQSGFSINSQVFAADGASTETSASGTSQGE","AGQPEVLSSQEMQVENELEDLIDELLERDG","PLILQRLLGPSAAADILQLSSSLPLQSRGR","SEPLLPLDEEAVDMDYGDMAVDVVDGEQES","DEEAVDMDYGDMAVDVVDGEQESSRDMEIS","KTLRRSYSPSMLDYDTENLNSEEIYSSLRG","HQDRQSQTKSMILTDAGKVTEPISRHRRNH","RKREEAAAVPAAAPDDLALLKNLRSEEQKK","NSAKEYRGTLRVTFDAEAMNKESPMVRSAR","SSSAHSVDSEDMYADLASPVSSASSRSPAP","SHSDMKSERRPPSPDVIVLSDNEQPSSPRV","AAASSSLERSYELPDGQVITIGNERFRCPE","QGAPAPGPSANVASDAMSILETITSLNQEA","PSCGGTTKKHSLEGDEGSDFITKNRNLVSS","GLAPAGGADNLINEESDVDVQLNNRHMMIR","RTDGKVFQFLNAKCESAFLSKRNPRQINWT","EPEEYVEEPAGVMPEEAADLDAEAMPESLR","EKKNERLRAAFGISDSYVDGSSFDPQRRAR","GTPPRPGSVTNMQADECTATPQRQSHSESS","KEAGIVTEPLGEMVDSSGASEEAAVDPGSV","LQQSVVKTYEDMTLEELEENEDEFSEEDER","KKGRSKGDKPEAETDSVQMANEELRAKLTN","EREMFDRASLKLGLDKAVLQSMSGRDSNVS","XXXXMALVGSRVELDADEDIFEDALETISR","XXXXXXMDSEYYSGDQSDDGGATPVQDERD","SESDSEDPPRPQASDSENEEPPKPRISDSE","DSEEEEPKRQKIDSDDDEEKEGDEEKVAKR","LEEEKNETQLKEAEDSDSDDNIKRGKHMDF","RSKKRTKRSSVVFADEKAATESDLKRLSRK","IAAPDVKLNLGVSGDFIKESTATTFLRQRG","RRQSSGDGVSCAASDYLVGQVADSLRGGPR","QAIRIIQERNGVLPDCLTDGADVVSDLEQE","PETIPDMEDSPPVSDSEEQQESVRAAPEKS","SHSDMKSEKRPPSPDVIVLSDSEQPSSPRV","QQSRKGWSGPDVIIEAQFDDSDSEDRHGNT","RKKKAKKRDSETIEDVAVEPLPLPGSPVRG","PRDLTLDALLEMNEAKVKETLRRCGASGDE","XXXXXXXXXXXMLTDSGGGGTSFEEDLDSV","GGSGSGTGGGDAALDFKLAAAVLRTGGGGG","KVLETPQEIRTVSSEAVSLLEEVITPRKDL","NAPFDPHSMDSHSGDIAVIEEVRLDNPKEG","SSMVESEVMKSLGKDGGLDDDEEEEDLDEG","PDTDFDFEGNLALFDKAAVFEEIDTYERRS","XXXXXXXXMEEVVAEELDDEEQLVRRHRKE","FIEMATTEDAQAAVDYYTTTPALVFGKPVR","PQAAEGHYTVSYGTDSGEFSSVGEEFYRNH","ENEFQIPGRTRPSSDQLKEASGTDVKQLDQ","QEAQGETEPTEQAPDALEQAADTSRRNAET","IKRGKRKRLSSVMCDSDESDDSDILVRKVG","ELKEHVLTQCKEAKNYEKTLQELITRRAIL","FVLHKSKSEEAHAEDSVMDHHFRKPANDIT","AEIRYEGILYTIDTENSTVALAKVRSFGTE","QPSMQELSKLQDMYDELMMIIGSRRSGLNQ","RPSSPRFSSLDLEEDSEVFKMLQENRQGRA","MESSEPEPTEDASMDAFLEKFQSQPYRGGF","EGVRVNNRFELINTEDLEDDLVVNGERSDC","EAGEEDGGSDGMGGDGSEFLQRDFSETYER","SHRATANTEEIIEGNSVDSSIQQVMGSGGQ","ATANTEEIIEGNSVDSSIQQVMGSGGQRVI","YNTKGCFAVHRITVEEAKYKLCKVRKITVG","TSDPAGGGESAASPEELEDEDAEGGGAARR","EPTREQLDSGRIGADEEIDDFKGRSAEEVE","HHISSCDDRSCIEQDVVNQTRSLRQETLAE","NSTSLKEKEHNKEPDSSVSKEVDDKDAPRT","FLDAVMLEREGMGMDQGPQEMIDRYLSLGE","RRSEPERGRLTPSPDIIVLSDNEASSPRSS","ENIQSSPPRLTKPQSVAIKRKRPFVLKKKR","LKEEEIHIYQFPECDSDEDEDFKRQDAEMK","KRLLKEEDMTKVEFETSEEVDVTPTFDTMG","AGPAKPSLALNPQEDSQFEKALTQIQGRTK","AVAHRDSEGNQVLPDQKEGLSGEPRRKEKM","LKHLEPEPEEEIIAEDYDDDPVDYEATRIE","KHLEPEPEEEIIAEDYDDDPVDYEATRIEG","XXXXXXMSAQSVEEDSILIIPNPDEEEKIL","IEEHLNCTISQVEPDIKVPVDEFDGKVTYG","KSKGGGKMNEEISSDSESESLAPRKTEEEE","AELSRKELGLEEGVDNLKALIQSRQKDRQK","ENPLKRGLVAAYSGDSDNEEELVERLESEE","SLAGIKRARARADGDSDAEDPGAPPEAVGA","MEELKVSFSKGIGTDSAEFAELKTQIERLR","KWHVINQRSILCGEDEIAEDNPESQEMLEE","XXXXXXXXXXXMAADTQVSETLKRFAGKVT","DDDEVSEEEEEFGLDEEDEDEDEDEEEEEG","EVSEEEEEFGLDEEDEDEDEDEEEEEGGKG","SEEEEEFGLDEEDEDEDEDEEEEEGGKGEK","EEEEEFGLDEEDEDEDEDEEEEEGGKGEKR","EEEFGLDEEDEDEDEDEEEEEGGKGEKRKR","EEFGLDEEDEDEDEDEEEEEGGKGEKRKRE","AQDPALVPPQEIAPDASFIDDEAFKRLQGK","HSDEYIKFLRSIRPDNMSEYSKQMQRFNVG","DTDQTLKKEGLISQDGSSLEALLRTDPLEK","KDSENTPVKGGTVADLDEQDEETVTAGGKE","AVQRARQIAAKIGGDAATTVNNSTPDFGFG","LLLTPREPALPLEPDSGGNTSPGVTANGEA","LLVQAYQQCFSDKERQNLLADIQVRRGEGV","TLTQFDSNIAPADPDTAIVHPVPIRMTPSK","AALNAQHKQGKVGPDGKELIPQESPRVGGF","ELCVDAAGHFPIGPDVEDLVKEAVSQVRAE","ANEGKKETWDTAEEDSGTDSEYDESGKSRG","AKVDEFPLGGHMVSDEYEQLSSEALEAARI","RATPSKPSGLSLLPDYEDEEEEEEEEEGDG","PTPTFHSSRTSLAGDTSNSSSPASTGAKTN","QVAPESRNRIRVRQDLASLPAELINQIGNR","QMLQGKPLADTMRPDTLQDYFGQSKAVGQD","XXXXXXXMAAAAECDVVMAATEPELLDDQE","YQKGFSDKLDFLEGDQKPLAQRKKAGAKGQ","LYNKFKNMFLVGEGDSVITQVLNKSLAEQR","QQLVASHLEKLLGPDAAINLADPDGALAKR","TKAFRKAAGKELTVDNSFEFEKRRNEPVKY","DRENMDTDDERQYQDFLEDLEEDEAIRKHV","EEKIEEANGRETTGDGEVDLLTKELEDFEM","EEANGRETTGDGEVDLLTKELEDFEMKKAA","KEEELRTAAGEYDSDSESEDEEMMEIRQLA","XXXXXXMPGKLLWGDIMELEAPLEESESQR","XXXXXXXXXXMEELDALLEELERCTFQDSE","EEEVSEVESFILDQDDLENPMLETASKLLL","NSQDVQGYITNQSPESIVEEAQGKLTELEQ","TQGRTCGSGRDLSGDSGTAEDLSLLSAKPQ","ENEEELGDEAMMALDQSLASLFAEQKLRIQ","KRKKRKSEDGTPAEDGTPAATGGSQPPSMG","KLSLIGKGKRRRSSDEDAAGEPKAKRPKYT","HYAMDNITRQNQFYDTQVIKQENESGYERR","KKLYCQELKKVIEASDVVLEVLDARDPLGC","NKIMHPVSGKHILQFVAIKRKDCGEWAIPG","MGCTWGMGEDAVEDDAEENPIVLEFQQERE","AQIRYEGILYTIDTDNSTVALAKVRSFGTE","ARPAKRPVFPPLSGDQLLTGKEETRKIPVP","PSSTPVLYTQNVEPDSGEAELDSRDLEMSQ","GKPECRVGQYVVNLDSFEQLALPVLRNAGS","LQTFLAQEDTEQSPDALASEDASRQKATET","PSPQTVPAAPAVDPDLYTASQGDIRLTPED","XXXXXXMTKVKAAPEESEAQAEGCSEERTY","LPPEDDDQWLDLSPDQLDQLLQDAAGRKES","MAQSIYRPSKNLDKDMYGDDLEARIKTNRF","AADVSVTHRPPLSPEAEAEAETPETVDRRA","PGHSKGELAPELGEDTQSLSQEETELELLR","GFGSEEGSRARMREDYDSVEQDGDEPGPQR","DSVVMAEAPVGVETDLIDVGFTDDVKKGGP","XXXMDPTCEESPAEDSNNEEEDLDSTKAAP","IRRVGRRPDQQLQGDGKLIDRRAERRPPRE","DSPQARPAASAMDEDALTLEELEEQQRQIW","RGSGKKRKFQPLFGDFAAEKKNQLELLRVM","DKKREWEMLCRVKPDVVKDKEAERNLQRIA","LKEVFSMAGVVVRADILEDKDGKSRGIGIV","NRAEAAEEDETVEVDVSDEEMARRYETLVG","VPKEEQNDPNTVKVDSKKMPRDITNTRDQR","LNEEKLEKLEEITMDGAKAKAILDASRSSM","AKAILDASRSSMGMDISAIDLINIESFSSR","RKNLDVMKEAVVQAEEAAAEITRKLEKQEK","XXXXXXMEGQRVEVDGGIMEGGGQILRVST","GSERADGRIVKMEVDYSATVDQRLPECEKL","PGGRGGGASTRVEEDSDSETYGEENDEQGN","ASQSLEEEKYKLLAEAAVELQEENTRQERI","AASLSQQTPSLPGSDSEEEEEVGRKKRHLQ","SLWFSKDGFSGIEDDADEALEISQAQLLYK","FPLYEEPDAKLARADSDGDLSENDDGAGDL","LYEEPDAKLARADSDGDLSENDDGAGDLRS","SPAKLNQSGASVGTDEESDVTQEEERDGQY","TLKLPPTFFCGVCSDTDEDNGNGEDFQSEL","GEEEEFGHDGEVDEDEEDEDEDEDEEEEES","EEFGHDGEVDEDEEDEDEDEDEEEEESGKG","YIDYSDSGKNTLVTEAVQAPQLAAEAVNVI","TLVTEAVQAPQLAAEAVNVIKRKRDSESES","EHLIGKKLPGFPTQDDEVMMLTERVAEAQR","RLLRCQRPAKDLPAAGSEMQIRPIVMSQKD","QLIENADACFCIDNEALYDICFRTLKLTTP","DDSYVSDISDNLSLDNLSNDLDNERQTLGP","KMIENEKLTMELTGDSMEVKPIMTRKLRRR","GAVLQEQNQDAVATELGILGMEGTIDRSRQ","NVTDVSLGISSNEQDQGSDKGENEAMESSG","GKQTMGFPLLTYQDRSDNKLYRLQTPQSPL","TLQENVNKYQQVKTDTSQESKAQANCRVGV","KWQVINQRSLLCGEDEAADENPESQEMLEE","EQPFNDSGCLLVDKDLFETGLEDENNSPLE","EREMFDKASLKLGLDKAVLQSMSGRDGNIT","AQTMIEHNSTMLESDLGTMVINSEEEEEEE","XMPGKLRSGAKLGSDGAEESMETLPKPSEK","PKPKKMKKGKEASGDAGEKSPRLKDGLSQP","GAVLQEQNQDAVATELGILGMEGSIDRSRQ","DEVRAGTYRQLFHPEQLITGKEDAANNYAR","SSAESSAGEDEWEYDEEEEKNQLEIERLEE","SQDNDQPDYDSVASDEDTDVETRASKANRQ","VVDPETGRTRLIKGDGEVLEEIVTKERHRE","MVTKYQKKKNKLEGDSDVDSELEDRVDGVK","MIAQAGWEMFRAGHRTPLSDSGVTQRYRTD","APVPTAPAAGAPLMDFGNDFVPPAPRGPLP","PGGWGAGASAPVEDDSDAETYGEENDEQGN","XXXXXXXMPGKLRSDAGLESDTAMKKGETL","CADHSRLVESKVELNALMTDETISNVPILI","ASRSTRHSHGPLQADVFVELLSPRRKRRGR","EDEEDDSEDAINEFDFLGSGEDGEGAPDPR","EPPSGRTESPATAAETASEELDNRSLEEIL","PTNNTPKGILHLSPDVYQEMEASRHKVISG","EELAQSDTSTEEQEDKAVQVSNKKKRKLPS","SDTFAPSPDKTIDCDVITLMGTPSGTAEPY","ETEDYRQFRKSVLADQGKSFATASHRNTEE","SGSSPKWTHDKYQGDGIVEDEEETMENNEE","LLQKWASMWSSMSEDASVADMERAQLEEEA","EMLSNQMLSGIPEVDLGIDAKIKNIISTED","HYATKKSVAESMLDVALFMSNAMRLKAVLE","KVMMYRKEQYLDVLHALKVVRFVSDATPQA","XXXXXXXMAATAECDVVMAATEPELLEDED","ATAECDVVMAATEPELLEDEDAKREAESFK","DLLPSRPEVPNVIGETEEVELQEFDSTRGS","EAGEPTPGLSDTSPDEGLIEDFPVDDRAVE","SNSELTPSESLVTTDDETFEKNFERETHKV","SEVYDAKGPKNVRSDVSDQEEDEESERCPV","GTSSHSADTPEASLDSGEGPSGMASQGCPS","TAVVQAALCKPRQERVAIKRINLEKCQTSM","FKPNQYTKIDTIAADESFTQMDLGDRILKL","AEKNEANGRETTEVDLLTKELEDFEMKKAA","RNEKAPVDFGYVGIDSILEQMRRKAMKQGF","GPQLLEELDNAPGSDAAELELAPARTPPDS","KKPPVKPPTEPIGFDLEIEKRIQERESKKK","RINQRLDMVPHLETDMMQGGVYGSGGERYD","SDGDDFEDATEFGVDDGEVFGMASSALRKS","XXXXXXXXXXXXMEDSSLPVVPAPIAAPGP","DIYHCPNCEKTHGKSTLKKKRTWHKHGPGP","SGDGKAIGVLTSGGDAQGMNAAVRAVVRMG","AVRLPLMECVQMTQDVQKAMDERRFKEAVK","TAYVGNLPFNTVQGDIDAIFKDLSIRSVRL","ELQRQLAEEEPMDTDQGSTVLSAIQSEVAR","SLPDTLEEASETEEDGGEDSDALPRGLRSK","KDEDRKELKDLFELDSSEGEDSTDFFERGV","SVLKDPDSNPYSLLDTSEPEPPVDSEPGEP","PFKPYNFLAHGVLPDSGHLHPLLKVRSQFR","PSSVVLHDEGQNEEDVEKEEETERMLKTAV","SFSITREAQVNVRMDSFDEDLARPSGLLAQ","SRMLAAKTVLAIRYDAFGEDSSSAMGVENR","YEHKSEVKTYDPSGDSTLPTCSKKRKIEQV","SDLDDQHDYDSVASDEDTDQEPLRSTGATR","DKRLEWEMMCRVKPDVVQDKETERNLQRIA","STQDSGLQESEVSAENILTVAKDPRYARYL","EPLLDPVGPEPLGPESQSGKGDMVEMATRF","SALQPEAGVCSLALPSDLQLDRRGAEGPEA","LYGQSVEDDYCISPSTAAQFIYSRRDKPSV","KPAVERCLEELVFGDVENDEDALLRRLRGP","PPASDLPTPQAIEPQAIVQQVPAPSRMQMP","KDKGKLEEKKPPEADMNIFEDIGDYVPSTT","MESEAGADDSAEEGDLLDDDDNEDRGDDQL","LERDDGSTMMEIDGDKGKQGGPTYYIDTNA","SAGYGGYEEYSGLSDGYGFTTDLFGRDLSY"};
    private String[] iMouseGranzymeBSubstrates = new String[]{"GHISVKEPTPSIASDISLPIATQELRQRLR","HPEAAQMVRREFQLDLDEIENDNGTVRCEM","EREMFDKASLKLGLDKAVLQSMSGRENATN","XXXXXXMSDIVVVTDLIAVGLKRGSDELLS","GQDQEEEEIEDILMDTEEELMRAEDTEQLK","RPSETKEVEPEPTEDKDLEADEEDTRKKDA","SKDKEKERERKSESDKDVKQVTRDYDEEEQ","XXXXXXXXXMEVTGDAGVPESGEIRTLKPC","SFSKEELMSSDLEETAGSTSIPKRKKSTPK","DTNHNEEDDEEPIPESSELTLQELLGDERR","VKAMAQEDSESLEEDSSSEEEDETPAQATP","GALSEEEAQALLSGDTQTDTTSFYDRVWAA","DLYDEFGNYIGPELDSDEDDDELGRETKDL","ARLIPDTVLVDLVSDSDEEVLEVADPVEVP","VPVARLPAPAKPEQDSDSDSEGAAEGPAGA","HMECEIKLEGPVSPDVEPGKEETEESKKRK","RLTEEEEAEPGTEVDLAVLADLALTPARRG","EGDDKDDYWREQQEKLEIEKRAIVEDHSLV","MMVPGMEGKEEPGSDSGTTAVVALIRGKQL","PQVTEAEEEEAPCCSSSVSGGAASSSPAAG","LLKRRNVPQEDICEDSDIDGDYRVQNTSLE","SGEEEEDEEGYNDGEVDDEEDEEEAGEEEG","EEEEDEEGYNDGEVDDEEDEEEAGEEEGSQ","EEDEEGYNDGEVDDEEDEEEAGEEEGSQKR","AGEEEEKEAGIVHSDAEKEQEEEEQKQEME","SDRSRKRELKEVFGDDSEISKESSGVKKRR","SGEDRDTKEALKEFDFLVTSEEGDNESRSA","GGEDKKETPEEVAADVLAEVITAAVRAVDG","SVLDNFKFLESAAADFSDEDEDEDTDGRAK","TSEDRDTKEALKEFDFLVTSEEGDNESRSA","GLGELAGLTVANEADSLAYDIANNKDALRK","LSELEKFEDQPEGIDLEVVTESTGKEREHN","YSVYVYKVLKQVHPDTGISSKAMGIMNSFV","DIYHCPNCEKTHGKSTLKKKRTWHKHGPGQ","RSTTLDAGNIKLAFNSLLEKAEAREREREK","GNLPFLKPDDIQYFDKLLVDVDESTLSPEE","PDDIQYFDKLLVDVDESTLSPEEQKERKIM","RSRRERVRQSRMDTDLETMDLDQGGEALAP","AAAAAAGDSDSWDADAFSVEDPVRKVGGGG","MDKMMVAGFKKQMADTGKLNTLLQRAPQCL","TEMGPPPSPASTCSDASSIASSASMPYKRR","ADLSKYNLDASEEEDSNKKKSNRRSRSKSR","GHSEASLASALVEGEIAEEAAEKATSRGSN","VERDDGSTLMEIDGDKGKQGGPTYYIDTNA","QLVENTDETYCIDNEALYDICFRTLKLTTP","ETGAGKHVPRAVFVDLEPTVIDEVRTGTYR","SITASLRFDGALNVDLTEFQTNLVPYPRIH","LYAVKILKKDVVIQDDDVECTMVEKRVLAL","YRRLLEDGEDFNLGDALDSSNSMQTIQKTT","XXXXXXXXMSDAAVDTSSEITTKDLKEKKE","REIFDSRGNPTVEVDLFTSKGLFRAAVPSG","YSIYVYKVLKQVHPDTGISSKAMGIMNSFV","SDEHGIDPTGTYHGDSDLQLDRISVYYNEA","NWAKGHYTEGAELVDSVLDVVRKEAESCDC","PGNPPAEIGQNISSNSSASILESKSLYDEV","LTFGFVRADDEVDVDGTVEEDLGKSREGSR","LQAQIQEQHVQIDVDVSKPDLTAALRDVRQ","TLRGQVGGQVSVEVDSAPGTDLAKILSDMR","LGRTLGLYGKDQQEAALVDMVNDGVEDLRC","EEDEDDEDEDDEEEDDEDDDEEEEEEEPVK","RTLLAKNLSFNITEDELKEVFEDAMEIRLV","KSKGIAYIEFKSEADAEKNLEEKQGAEIDG","SQPSKTLFVKGLSEDTTEETLKESFEGSVR","IVDKYRDGTKMVSADAYKITPGARGAFSEE","SNFGGGGSYNDFGNYNNQSSNFGPMKGGNF","XXXXXXMAGGKAGKDSGKAKTKAVSRSQRA","PTRPTDKPLRLPLQDVYKIGGIGTVPVGRV","GKKLEDGPKFLKSGDAAIVDMVPGKPMCVE","AAIVDMVPGKPMCVESFSDYPPLGRFAVRD","PKSKELVSSSSSGSDSDSEVEKKLKRKKQA","SKELVSSSSSGSDSDSEVEKKLKRKKQAVP","PPYRGRSSESSCGVDGDYEDAELNPRFLKD","YRGRSSESSCGVDGDYEDAELNPRFLKDNL","AGPKTLKKKVPAVPETLKKKRRNFAELKVK","GALSEAEAQALLSGDTQTDATSFYDRVWAA","SEKDIQDLKFGVEQDVDMVFASFIRKASDV","LTFGSVRADDEVDVDGTVEEDLGKSREGSR","REIFDSRGNPTVEVDLYTAKGLFRAAVPSG","REILDSRGNPTVEVDLYTAKGLFRAAVPSG","XXXXXXXXMDGIVPDIAVGTKRGSDELFST","QSGNLALAASAAAVDAGMAMAGQSPVLRII","LYAIKILKKDVVIQDDDVECTMVEKRVLAL","ISNNVPGTDFSLGSDTAVNAAMESCDRIKQ","LGQAEEVVQERICDDELILIKNTKARTSAS","EGVEEKKKEVPAVPETLKKKRRNFAELKIK","DGNIDLESDSFLKFDSEPSAVALELPTRAF","XXXXXXMPKRKVSADGAAKAEPKRRSARLS","RTLLAKNLPYKVTQDELKEVFEDAAEIRLV","KSKGIAYIEFKTEADAEKTFEEKQGTEIDG","QPSETKEVEPEPTEDKDLEADEEDTRKKDA","VRLRSSVPGVRLLQDSVDFSLADAINTEFK","KHLKRVAAPKHWMLDKLTGVFAPRPSTGPH","LRMHQYRAPGEQDGDALPLGSSVDILATDD","GEQDGDALPLGSSVDILATDDPDFTQDDQQ","DDSQEKTDDSQETQDSQKVELSEPRLKAFK","AEMSSILEERILGADTSVDLEETGRVLSIG","EEEEEEEEGDGEEEDGDEDEEAEAPTGKRV","GQIPATALLPTMTPDGLAVTPTPVPVVGSQ","IPATALLPTMTPDGLAVTPTPVPVVGSQMT","LILFPRKPSAPKKGDSSAEELKLATQLTGP","PMSAPSRSSGALSVDKKPTSTKPSSSAPRV","IHISKKWGFTKFNADEFEDMVAEKRLIPDG","RLEQQVPVNQVFGQDEMIDVIGVTKGKGYK","QVPVNQVFGQDEMIDVIGVTKGKGYKGVTS","XXXXXXXMADLSLADALTEPSPDIEGEIKR","VTLAKDMQPSMESDMALVKDMELPTEKEVA","DSSVSYIDSAVISPDTVPLGTGTSILSKQV","LRRRTFSYDEIHGQDSGAEDSIAKQIESLE","SPPQMHSSAIPLDFDVSSPLTYGTPSSRVE","XXMSGFDDPGIFYSDSFGGDAQADEGQARK","GALARGDDETLHKNNALKVVRELQAQIAEL","LSQRYYEDLDEVSSTSSVSQSLESEDARTS","RSRILKAGGKILTFDQLALESPKGRGTVLL","RRIQRRGPCIIYNEDNGIIKAFRNIPGITL","IPPPYDKKKRMVVPAALKVVRLKPTRKFAY","GLIHRKTVGVEPAADGKGVVVVMKRRSGQR","SLSDEAPVLPNTTPDLLLVTTANPSAPGTD","AMNRHIKASTKVEVDMEKAESLQVTRGDFL","GKTDYYARKRLVIQDKNKYNTPKYRMIVRV","GMDKIYEGQVEVTGDEYNVESIDGQPGAFT","GLIHRKTVGVEPAADGKGVVVVIKRRSGQR","VSNNVPGSDFSIGADTALNTICTTCDRIKQ","CGYLATMAGLAAGADAAYIFEEPFTIRDLQ","KQLRKPRHQEGEIFDTEKEKYEITEQRKAD","ENEEEEIGNLELAWDMLDLAKIIFKRQETK","EPEPDYEPEPETEPDYEDVGELDRQDEDAE","XXMSGFDDPGIFYSDSFGGDPGAEEGQARK","GDGMERDYRAIPELDAYEAEGLALDDEDVE","HEKAEFEVHEVYAVDVLVSSGEGKAKDAGQ","PNGPMRITSGPFEPDLYKSEMEVQDAELKA","PRGTLRRDFNHINVELSLLGKKKKRLRVDK","KARKTGLITPKAGFDSDYDQALADIRENEQ","KQEGSSDDASSGVGDSDSEDLGTFGKGAPK","MADIDNKEQSELDQDLDDVEEVEEEETGEE","GNRSSHSRLGRIEADSESQEDIIRNIARHL","FGRTTTPQQTKITQDIFQQLLKRGFVLQDT","EDEEDDSEDAINEFDFLGSGEDGEGSPDPR","XXXXMDDDIAALVVDNGSGMCKAGFAGDDA","IVRDIKEKLCYVALDFEQEMATAASSSSLE","AASSSSLEKSYELPDGQVITIGNERFRCPE","SDGLKGRVFEVSLADLQNDEVAFRKFKLIT","LRQKYNVRSMPIRKDDEVQVVRGHYKGQQI","GYDYSYAGGRGSYGDLGGPIITTQVTIPKD","FESGISQALLELEMNSDLKAQLRELNITAA","KQKRPRSRTLTAVHDAILEDLVFPSEIVGK","RSRTLTAVHDAILEDLVFPSEIVGKRIRVK","ALPLGRKKGAKLTPEEEEILNKKRSKKIQK","XXXXXXMVRMNVLADALKSINNAEKRGKRQ","QPTIFQNKKRVLLGETGKEKLPRYYKNIGL","IDLETGKITDFIKFDTGNLCMVTGGANLGR","YDIDVAKVNTLIRPDGEKKAYVRLAPDYDA","ERKRKSVRGCIVDANLSVLNLVIVKKGEKD","RKFTYRGVDLDQLLDMSYEQLMQLYSARQR","KRTFRKFTYRGVDLDQLLDMSYEQLMQLYS","YRGVDLDQLLDMSYEQLMQLYSARQRRRLN","KGKVRDKLNNLVLFDKATYDKLCKEVPNYK","YARRPQYSNPPVQGEVMEGADNQGAGEQGR","RFRRGPPRQRQPREDGNEEDKENQGDETQG","XXXXXXXXXXXMQNDAGEFVDLYVPRKCSA","XXXXXXXMADDLDFETGDAGASATFPMQCS","XXXXMADDLDFETGDAGASATFPMQCSALR","XXXXMEEEIAALVIDNGSGMCKAGFAGDDA","RLGNDFHTNKRVCEEIAIIPSKKLRNKIAG","TGAGKHVPRAVFVDLEPTVIDEVRTGTYRQ","DEVRTGTYRQLFHPEQLITGKEDAANNYAR","VGINYQPPTVVPGGDLAKVQRAVCMLSNTT","ETGAGKHVPRAVFVDLEPTVIDEIRNGPYR","DEIRNGPYRQLFHPEQLITGKEDAANNYAR","ACISIGNQNFEVKADDLEPIVELGRGAYGV","QALQAGELESQAAPDEAQGDPELGAVELRI","GVQMQAIPEDAVHEDSGDEDGEDPDKRISI","TQTATQQAQLAAAAEIDEEPVSKAKQSRSE","SPARPPSPRLDVSSDSFDPLLALYAPRLPP","AGAGSSGGSSGVSGDSAVAGAAPALVAAAA","AKVDEFPLCGHMVSDEYEQLSSEALEAARI","GDGMERDYRPIPELDVYEAEGLALDDEDVE","KDEIQDEEDDDDYVDEGEEEEEEEEEGLRG","IQDEEDDDDYVDEGEEEEEEEEEGLRGEKR","GGGGGGRPGAPAAGDGKTEQKGGDKKRGVK","VSNNVPGSDFSIGADTALNTITDTCDRIKQ","NVPGSDFSIGADTALNTITDTCDRIKQSAS","CGYLANMGGLAAGADAAYIFEEPFDIRDLQ","PLDPTRLQGINCGPDFTPSFANLGRTTLST","FFAIKALKKDVVLMDDDVECTMVEKRVLSL","YFAIKALKKDVVLIDDDVECTMVEKRVLTL","APDPALVPPQEIAPDASFIDDEAFKRLQGK","ASEEGADRNGGPGEDAAEGQTKTAAGKRKR","EREMFDKASLKLGLDKAVLQSMSGRDGNIT","AALEKLFPDTPLALDANKKKRAPVPVRGGP","DFPIPLPEDDSIEADILAITGPEDQPGSLE","QRMRVSSGERWIKGDKSELNEIKENQRSPV","NWAKGHYTEGAELVDSVLDVVRKECENCDC","QLVENTDETYCIDNEALYDICFRTLKLATP","QQLVASHLEKLLGPDAAINLTDPDGALAKR","NWAKGHYTEGAELVDSVLDVVRKESESCDC","QLVENTDETYSIDNEALYDICFRTLKLTTP","VRTMLDEDDVKVAVDVLKELEALMPSAAGQ","DLPISRENLTDLVVDTDTLGESTQPQREGA","KRSSSEDDDLDVESDFDDASINSYSVSDGS","PEIRKRYDQDLCYTDILFTEQERGVGIKST","AAATNHTTDNGVGPEEESVDPNQYYKIRSQ","TKSGSRGTERTVVMDKSKGVPVISVKTSGS","SESPSASVAEATTTDVQVTPTALLQLDREQ","EGDDVQTAAEEVLADGDTLDFEDDTVQSSG","DDVQTAAEEVLADGDTLDFEDDTVQSSGPR","ADRCTLPEHESPSQDISDACEAESTERCEM","EREMFDRASLKLGLDKAVLQSMSGRESNVG","PTLPVEEKKKIPDPDSDDVSEVDARHIIEN","SILKSRSRENSVCSDTSESSAADVEDRRGL","AVQRARQIAAKIGGDAATTVNNNTPDFGFG","FFKWQTKPKLTIHGDLYYEGKEFETRLKEK","DEDKPDETGFITPADSGLITPGGFSSVPAG","ASGDPKKEKKSLDSDESEDEDDDYQQKRKG","PPPVSSSDSEAPEADLGCGSDVDKDKESRR","SEDLGVVIDEEPASELSETQGATELPEEER","EDGNYSAVGFTYGSDYYDPSEPTEEEEPSK","TCRDANEELNCQDPDVGDMEEEERLQVTDK","PCPSPSPRRTSPAPDILSLPEDPCLGPRNE","EAEQLEPRVSALEEDMDDVESSEEEEEEDE","APKPRKVELSESEEDKGSKMAAADSVQQRR","KPAAERCLEQLVFGDVEDDEDALLQRLRSS","QEDQTSDKNEGISEDMGDEAKEERQESRAS","EYAKIHDLLKTIGLDIGVAEISQLAARTQE","EPSAPDCRHLKVEADAEKPGPADRKGGLGM","RNVAPKNYSETIEVDDSDEDDIFPTNSRAD","FLDNGPKTINQIRQDAVKDLGVFIPAPMAQ","YNKAVECCDKALGLDSANEKGLYRRGEAQL","AAAAAAGDSDSWDADTFSMEDPVRKVAGGG","RLMPNSQKDCHCLGDVLIENTKESKSQSED","NPETKPARPDPIDMDEDELEMLSEARARLA","VFKAPAPRPSLLGLDLLASLKRREREEKDD","GYCKLKVFNPRIGMDALQIYPISQANANQR","SGAGSEDMSTTVNGDVFQEANGPADGYAAI","STVNEKPKYAEISSDEDNDSDEAFESSRKR","LHKSEKSSQQVVEQDNLFDVSTEEGPIKRK","IKLPSSVFASEFEEDVGLLNKAAPVSGPRL","DRDYMDTLPPTVGDDVGKGAAPNVVYTYTG","IPPPYDKKKRMVVPAALKVVRLKPTRKFAL","RAAALDAGNIKLTFNSLLEKAEAREREREK","QLDPSRLPGINCGPDFTPSFANLGRPALSN","DSPQTRTASGAVDEDALTLEELEEQQRRIW","KAKIMAKKRSTIKTDLDDDITALKQRSFVD","DLNGLLVPDPLCSGDSTSANKTGLRTMPPI","GPGNPVPGPLAPLPDYMSEEKLQEKARKWQ","KKAKGGNVFEALIQDDSEEEEEEEENRVLK","KAKGGNVFEALIQDDSEEEEEEEENRVLKP","XXMALFHIARYAGPEAAGQGDTDAEAGSRA","PKIPKSKRQKKELGDSSGEGPEFVEEEEEV","FRKTLEKEAKGEEPDIAVPKFKQRKGESDG","QQLMSKDQDEQEELDFLFDEEMEQMDGRKN","FWEPVESTQEVVCTDNATEKEEEADGGGQA","AAPAAAAPPPAPATDSASGPSSDSGPEAGS","DREDGELEEGELEDDGAEEVQDPPGGQERS","QAEEHGLARKKPAPDAQAESGPGDGGGEPD","DLRGKKKEELLKQLDDLKVELSQLRVAKVT","XXXXXXMAGGKAGKDSGKAKAKAVSRSQRA","DDRLEDDDFDLIEENLGVKVKRGQKYRRVK","SASLAKKKPLFITTDSSKLVSGVLGSALTS","XXXMSAQAQMRAMLDQLMGTSRDGDTTRQR","EEEEELGDEAMMALDQNLASLFKEQKMRIQ","PLGSDSEGVNCLAYDEAIMAQQDRIQQEIA","FSGSSTFSPTILSSDKETIEIIDLAKKDLE","PLILQRLLGPSAAADILQLSSSLPLQSRGR","SSIQAAVRQLEAEADAIIQMVREGQRARRQ","SEPLLPLDEEAVDMDYGDMAVDVVDGEQES","KTLRRSYSPSMLDYDTENLNSEEIYSSLRG","HQDRQSQTKSMILTDAGKVTEPISRHRRNH","RKREEAAAVPAAAPDDLALLKNLRSEEQKK","SSSAHSVDSEDMYADLASPVSSASSRSPAP","SHSDMKSERRPPSPDVIVLSDNEQPSSPRV","AAASSSLERSYELPDGQVITIGNERFRCPE","PSCGGTTKKHSLEGDEGSDFITKNRNLVSS","GTPPRPGSVTNMQADECTATPQRQSHSESS","KEAGIVTEPLGEMVDSSGASEEAAVDPGSV","EREMFDRASLKLGLDKAVLQSMSGRDSNVS","XXXXXXMDSEYYSGDQSDDGGATPVQDERD","LEEEKNETQLKEAEDSDSDDNIKRGKHMDF","PETIPDMEDSPPVSDSEEQQESVRAAPEKS","XXXXXXXXXXXMLTDSGGGGTSFEEDLDSV","APKPRKVELSESEEDKGGKMAAADSVQQRR","NAPFDPHSMDSHSGDIAVIEEVRLDNPKEG","SSMVESEVMKSLGKDGGLDDDEEEEDLDEG","PDTDFDFEGNLALFDKAAVFEEIDTYERRS","QEAQGETEPTEQAPDALEQAADTSRRNAET","ISDGSEVVVVKEELNSSVAIADTALEDRKN","TQMEFPDASFQVVLDKGTLDAVLTDEEEKT","EGVRVNNRFELINTEDLEDDLVVNGERSDC","EAGEEDGGSDGMGGDGSEFLQRDFSETYER","HHISSCDDRSCIEQDVVNQTRSLRQETLAE","AGPAKPSLALNPQEDSQFEKALTQIQGRTK","AVAHRDSEGNQVLPDQKEGLSGEPRRKEKM","KSKGGGKMNEEISSDSESESLAPRKTEEEE","AELSRKELGLEEGVDNLKALIQSRQKDRQK","SLAGIKRARARADGDSDAEDPGAPPEAVGA","AQDPALVPPQEIAPDASFIDDEAFKRLQGK","AVQRARQIAAKIGGDAATTVNNSTPDFGFG","VATMNEQGFCKIVGRSKDMIIRGGENIYPA","AALNAQHKQGKVGPDGKELIPQESPRVGGF","TDYSSADENILTKADTLKVKDRKKKKKKGQ","RSAILVTDKRVQTMNEFLTCIRLIKMYAWE","QVAPESRNRIRVRQDLASLPAELINQIGNR","HMMNAIKKYQKGFSDKLDFLEGDQKPLAQR","YQKGFSDKLDFLEGDQKPLAQRKKAGAKGQ","SALRDDERRESATADAGYAILEKKGALAER","TKAFRKAAGKELTVDNSFEFEKRRNEPVKY","EEKIEEANGRETTGDGEVDLLTKELEDFEM","EEANGRETTGDGEVDLLTKELEDFEMKKAA","KEEELRTAAGEYDSDSESEDEEMMEIRQLA","XXXXXXMPGKLLWGDIMELEAPLEESESQR","XXXXXXXXXXMEELDALLEELERCTFQDSE","GKKAALDEAQGVGLDSTGYYDQEIYGGSDS","TQGRTCGSGRDLSGDSGTAEDLSLLSAKPQ","SSSSGSQTDSSIEDAAKGKIKKKRREKTNK","KKLYCQELKKVIEASDVVLEVLDARDPLGC","ARPAKRPVFPPLSGDQLLTGKEETRKIPVP","PSSTPVLYTQNVEPDSGEAELDSRDLEMSQ","PSPQTVPAAPAVDPDLYTASQGDIRLTPED","XXXXXXMTKVKAAPEESEAQAEGCSEERTY","LPPEDDDQWLDLSPDQLDQLLQDAAGRKES","XXXMDPTCEESPAEDSNNEEEDLDSTKAAP","TPAEETRRTSEAGPDKETASTLVQEASPEL","XXXXXXXXXXXMAQDQGEKENPMRELRIRK","IRRVGRRPDQQLQGDGKLIDRRAERRPPRE","DSPQARPAASAMDEDALTLEELEEQQRQIW","RGSGKKRKFQPLFGDFAAEKKNQLELLRVM","NRAEAAEEDETVEVDVSDEEMARRYETLVG","VPKEEQNDPNTVKVDSKKMPRDITNTRDQR","LNEEKLEKLEEITMDGAKAKAILDASRSSM","AKAILDASRSSMGMDISAIDLINIESFSSR","XXXXXXMEGQRVEVDGGIMEGGGQILRVST","FPLYEEPDAKLARADSDGDLSENDDGAGDL","XXXXXXXMELEFLYDLLQLPKEVAQPTEEE","SPAKLNQSGASVGTDEESDVTQEEERDGQY","GEEEEFGHDGEVDEDEEDEDEDEDEEEEES","EEFGHDGEVDEDEEDEDEDEDEEEEESGKG","YIDYSDSGKNTLVTEAVQAPQLAAEAVNVI","RLLRCQRPAKDLPAAGSEMQIRPIVMSQKD","DGVEVSVTTSKIVTDSDSKTEELRFLRRQE","QLIENADACFCIDNEALYDICFRTLKLTTP","DDSYVSDISDNLSLDNLSNDLDNERQTLGP","AQTMIEHNSTMLESDLGTMVINSEEEEEEE","PKPKKMKKGKEASGDAGEKSPRLKDGLSQP","GAVLQEQNQDAVATELGILGMEGSIDRSRQ","SSAESSAGEDEWEYDEEEEKNQLEIERLEE","VVDPETGRTRLIKGDGEVLEEIVTKERHRE","APVPTAPAAGAPLMDFGNDFVPPAPRGPLP","XXXXXXXMPGKLRSDAGLESDTAMKKGETL","ASRSTRHSHGPLQADVFVELLSPRRKRRGR","EELAQSDTSTEEQEDKAVQVSNKKKRKLPS","DEVRAGTYRQLFHPEQLITGKEDAANNYAR","EMLSNQMLSGIPEVDLGIDAKIKNIISTED","KVMMYRKEQYLDVLHALKVVRFVSDATPQA","DLLPSRPEVPNVIGETEEVELQEFDSTRGS","EAGEPTPGLSDTSPDEGLIEDFPVDDRAVE","SEVYDAKGPKNVRSDVSDQEEDEESERCPV","AEKNEANGRETTEVDLLTKELEDFEMKKAA","KKPPVKPPTEPIGFDLEIEKRIQERESKKK","RINQRLDMVPHLETDMMQGGVYGSGGERYD","KGSSPGIQDTLEAEDGAFETDEAPEDRILS","DIYHCPNCEKTHGKSTLKKKRTWHKHGPGP","TAYVGNLPFNTVQGDIDAIFKDLSIRSVRL","ELQRQLAEEEPMDTDQGSTVLSAIQSEVAR","SLPDTLEEASETEEDGGEDSDALPRGLRSK","KDEDRKELKDLFELDSSEGEDSTDFFERGV","SVLKDPDSNPYSLLDTSEPEPPVDSEPGEP","SFSITREAQVNVRMDSFDEDLARPSGLLAQ","YEHKSEVKTYDPSGDSTLPTCSKKRKIEQV","DKRLEWEMMCRVKPDVVQDKETERNLQRIA","SALQPEAGVCSLALPSDLQLDRRGAEGPEA","KPAVERCLEELVFGDVENDEDALLRRLRGP","GFGSEEGSRARMREDYDSVEQDGDEPGPQR","LERDDGSTMMEIDGDKGKQGGPTYYIDTNA","SAGYGGYEEYSGLSDGYGFTTDLFGRDLSY","DSFREGETVVLTLKDKGVLQDGEDVLVNVN"};

    public IceLogoServiceTestCase(java.lang.String name) {
        super(name);
    }

    public void test1icelogoTestService() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String value = null;
        value = binding.testService("Check check double check");
        assert(value.equalsIgnoreCase("The service is running, your test string was : Check check double check"));
    }

    public void test2icelogoGetSamplingIceLogo() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String value = null;
        value = binding.getSamplingIceLogo(iHumanGranzymeBSubstrates, new String[0], "Homo sapiens", "percentage", 15, 0, 0.05, 600, 800, "regional", 14, 30, 1, "NtoC");
        assert(value.startsWith("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE svg "));
    }

    public void test3icelogoGetSamplingHeatMap() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String value = null;
        value = binding.getSamplingHeatMap(iHumanGranzymeBSubstrates,new String[0], "Homo sapiens", 0, 0.05, 600, 800, "regional", 14, 30, 1, "NtoC");
        assert(value.startsWith("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE svg "));
    }

    public void test4icelogoGetSamplingAaParameterGraph() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String value = null;
        value = binding.getSamplingAaParameterGraph(iHumanGranzymeBSubstrates,new String[0], "Homo sapiens", "Net charge (Klein et al., 1984)", 0, 0.05, 600, 800, "regional", 14, 30, 1, "NtoC");
        assert(value.startsWith("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE svg "));
    }

    public void test5icelogoGetSamplingConservationLine() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String value = null;
        value = binding.getSamplingConservationLine(iHumanGranzymeBSubstrates,new String[0], "Homo sapiens", "BLOSUM62 substitution matrix (Henikoff-Henikoff, 1992)", 0, 0.05, 600, 800, "regional", 14, 30, 1, "NtoC");
        assert(value.startsWith("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE svg "));
    }

    public void test6icelogoGetStaticIceLogo() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String value = null;
        value = binding.getStaticIceLogo(iHumanGranzymeBSubstrates, "Homo sapiens", "percentage", 10, 0, 0.05, 600, 800);
        assert(value.startsWith("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE svg "));
    }

    public void test7icelogoGetStaticHeatMap() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String value = null;
        value = binding.getStaticHeatMap(iHumanGranzymeBSubstrates, "Homo sapiens", 0, 0.05);
        assert(value.startsWith("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE svg "));
    }

    public void test8icelogoGetStaticSequenceLogo() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String value = null;
        value = binding.getStaticSequenceLogo(iHumanGranzymeBSubstrates, "Homo sapiens", 0, 600, 800);
        assert(value.startsWith("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE svg "));
    }

    public void test9icelogoGetFilledLogo() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String value = null;
        value = binding.getFilledLogo(iHumanGranzymeBSubstrates, 0, 600, 800);
        assert(value.equalsIgnoreCase("The service is running, your test string was : Check check double check"));
    }

    public void test10icelogoGetStaticAaParameterGraph() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String value = null;
        value = binding.getStaticAaParameterGraph(iHumanGranzymeBSubstrates, "Homo sapiens", "Net charge (Klein et al., 1984)", 0, 0.05, 600, 800);
        assert(value.equalsIgnoreCase("The service is running, your test string was : Check check double check"));
    }

    public void test11icelogoGetStaticConservationLine() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String value = null;
        value = binding.getStaticConservationLine(iHumanGranzymeBSubstrates, "Homo sapiens", "BLOSUM62 substitution matrix (Henikoff-Henikoff, 1992)", 0, 0.05, 600, 800);
        assert(value.equalsIgnoreCase("The service is running, your test string was : Check check double check"));
    }

    public void test12icelogoGetStaticReferenceSetIceLogo() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String value = null;
        value = binding.getStaticReferenceSetIceLogo(iHumanGranzymeBSubstrates, iMouseGranzymeBSubstrates, "percentage", 10, 0, 0.05, 600, 800);
        assert(value.equalsIgnoreCase("The service is running, your test string was : Check check double check"));
    }

    public void test13icelogoGetStaticReferenceSetHeatMap() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String value = null;
        value = binding.getStaticReferenceSetHeatMap(iHumanGranzymeBSubstrates, iMouseGranzymeBSubstrates, 0, 0.05);
        assert(value.equalsIgnoreCase("The service is running, your test string was : Check check double check"));
    }

    public void test14icelogoGetStaticReferenceSetSequenceLogo() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String value = null;
        value = binding.getStaticReferenceSetSequenceLogo(iHumanGranzymeBSubstrates, iMouseGranzymeBSubstrates, 0, 600, 800);
        assert(value.equalsIgnoreCase("The service is running, your test string was : Check check double check"));
    }

    public void test15icelogoGetStaticReferenceSetAaParameterGraph() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String value = null;
        value = binding.getStaticReferenceSetAaParameterGraph(iHumanGranzymeBSubstrates, iMouseGranzymeBSubstrates, "Net charge (Klein et al., 1984)", 0, 0.05, 600, 800);
        assert(value.equalsIgnoreCase("The service is running, your test string was : Check check double check"));
    }

    public void test16icelogoGetStaticReferenceSetConservationLine() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String value = null;
        value = binding.getStaticReferenceSetConservationLine(iHumanGranzymeBSubstrates, iMouseGranzymeBSubstrates, "BLOSUM62 substitution matrix (Henikoff-Henikoff, 1992)", 0, 0.05, 600, 800);
        assert(value.equalsIgnoreCase("The service is running, your test string was : Check check double check"));
    }

    public void test17icelogoGetAvailableAaParameters() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String[] value = null;
        value = binding.getAvailableAaParameters();
        assert(value.length == 544);
    }

    public void test18icelogoGetAvailableSubstitutionMatrices() throws Exception {
        IcelogoSoapBindingStub binding;
        try {
            binding = (IcelogoSoapBindingStub)
                          new IceLogoServiceLocator().geticelogo();
        }
        catch (javax.xml.rpc.ServiceException jre) {
            if(jre.getLinkedCause()!=null)
                jre.getLinkedCause().printStackTrace();
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre);
        }
        assertNotNull("binding is null", binding);

        // Time out after a minute
        binding.setTimeout(1000000);

        // Test operation
        java.lang.String[] value = null;
        value = binding.getAvailableSubstitutionMatrices();
        assert(value.length == 94);
    }



}
